# ░░█░▄▀█░█░█░█░█▄█
# █▄█░█▀█░▀▄▀░█▄░█░
#
# Автор: h1kyou (feat. er1one) (vk.me/h1kyou)
# Версия: 1.9
# Зависимости: WorldGuard, PlaceholderAPI
#
# Команды:
# /regions reload - Перезагружает конфигурацию (Право: regions.reload)
#
# Плейсхолдеры:
# %javlyregions_title% - Заголовок региона
# %javlyregions_name% - Название WorldGuard региона
# %javlyregions_custom% - Имя кастомного региона
# %javlyregions_owners% - Владельцы региона

# Сообщения
messages:
  no-permissions: "&cУ вас нет прав."
  config-reloaded: "&aКонфиг перезагружен."
  reload-usage: "&aИспользуйте: &e/regions reload"

# Настройки
settings:

  # Определяет, будет ли отображение постоянным или временным.
  # Если значение false, отображение будет временным и исчезнет после истечения времени.
  persistent-display: true

  # Определяет, будут ли отображаться регионы через ActionBar.
  # Если значение false, видим будет только BossBar.
  actionbar-enabled: true

  # Отображение через BossBar
  bossbar:
    # Будет ли отображение через BossBar
    enabled: false

    # Время в секундах, через которое BossBar исчезнет после его появления,
    # если отображение временное
    duration: 2.5

    # Цвет BossBar
    color: RED

    # Стиль BossBar
    style: SOLID

  # Частота обновления (в секундах)
  update_time: 1.5

  # Отключение отображения региона в конкретных мирах
  # Оставьте null, если не используется
  disabled-worlds: null
    # - "WORLD"
    # - "NETHER"
    # - "WORLD_THE_END"

# Форматы
formats:
  global: "&#888888▪ &#FFFF00&lНЕТ РЕГИОНА &#888888▪"
  region: "&#FF0000❌ &#FF0000&lТЕРРИТОРИЯ ЗАНЯТА &#CCCCCC(%javlyregions_name%) &#CCCCCC(%javlyregions_owners%) &#FF0000❌"
  owner: "&#FFFF00▪ &#00FF00&lВАШ РЕГИОН &#CCCCCC(%javlyregions_name%) &#FFFF00▪"
  member: "&#FFFF00▪ &#00FF00&lУЧАСТНИК РЕГИОНА &#CCCCCC(%javlyregions_name%) &#FFFF00▪"

# Кастомные регионы
custom-regions:
  spawn: "&e▪ &c&lСПАВН &e▪"                          # Формат для региона спавна
  shop: "&e▪ &c&lМАГАЗИН &e▪"                         # Формат для региона магазина
  pvp: "&e▪ &c&lПВП &e▪"                              # Формат для региона ПВП