name: JavlyRegions
version: '${project.version}'
main: dev.h1kyou.javlyregions.JavlyRegions
depends:
  - PlaceholderAPI
  - WorldGuard
author: h1kyou
website: https://vk.me/h1kyou
permissions:
  regions.reload:
    description: Allows the user to reload the plugin.
    default: op
commands:
  regions:
    description: Main command for the JavlyRegions plugin.
    permission: regions.reload